// <auto-generated />
using System;
using CitationNeeded.Database.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CitationNeeded.Database.Migrations
{
    [DbContext(typeof(CitationContext))]
    [Migration("20190923091854_UsernameToFirstAndLastName")]
    partial class UsernameToFirstAndLastName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CitationNeeded.Domain.ValueTypes.Citation", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CitationGroupId");

                    b.Property<string>("SpeakerId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("CitationGroupId");

                    b.HasIndex("SpeakerId");

                    b.ToTable("Citation");
                });

            modelBuilder.Entity("CitationNeeded.Domain.ValueTypes.CitationBook", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("CitationBooks");
                });

            modelBuilder.Entity("CitationNeeded.Domain.ValueTypes.CitationGroup", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuthorId");

                    b.Property<string>("CitationBookId");

                    b.Property<DateTime>("Created");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CitationBookId");

                    b.ToTable("CitationGroup");
                });

            modelBuilder.Entity("CitationNeeded.Domain.ValueTypes.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CitationNeeded.Domain.ValueTypes.Citation", b =>
                {
                    b.HasOne("CitationNeeded.Domain.ValueTypes.CitationGroup")
                        .WithMany("Citations")
                        .HasForeignKey("CitationGroupId");

                    b.HasOne("CitationNeeded.Domain.ValueTypes.User", "Speaker")
                        .WithMany()
                        .HasForeignKey("SpeakerId");
                });

            modelBuilder.Entity("CitationNeeded.Domain.ValueTypes.CitationGroup", b =>
                {
                    b.HasOne("CitationNeeded.Domain.ValueTypes.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("CitationNeeded.Domain.ValueTypes.CitationBook")
                        .WithMany("CitationGroups")
                        .HasForeignKey("CitationBookId");
                });
#pragma warning restore 612, 618
        }
    }
}
