name: CD

on: 
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.402' 
    - run: ls -la
    - run: dotnet restore
    - run: dotnet build
    - uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: alexandermenze/citationneeded
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: CitationNeeded.WebApp
